[book]
authors = ["Ellie Ang."]
language = "de"
multilingual = false
src = "src"
title = "Informatik TU Darmstadt 2021 - Notizen"

[output.html]
mathjax-support = true
no-section-label = true
default-theme = "rust"
