site_name: TUD D120 Notizen
theme:
  name: material
  features:
    - navigation.instant

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - _js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js